import "dotenv/config";
import e from "express";
import user_router from "./http/router/user_router.js";
import roullete_bet_router from "./http/router/roullete_bet_router.js";
import jackpot_bet_router from "./http/router/jackpot_bet_router.js";
const app = e();
// const port = 3000;
app.use(e.json());
app.use("/roullet", roullete_bet_router);
app.use("/user", user_router);
app.use("/jackpot", jackpot_bet_router);
app.listen(process.env.API_PORT, () => console.log("Servidor escutando "));
